---
# Runs only on host1
- hosts: host1
  become: true
  gather_facts: false
  tasks:
  - name: Install EPEL
    yum:
      name:
        - https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
        - epel-release
  
  - name: Install packages only on host1
    yum:
      name:
        - telnet
        - vim
        - nginx
        - postgresql 
        - zabbix-server-pgsql
        - zabbix-agent
        - centos-release-scl
      state: latest
    
  - name: Configure host
    script: ./task1.sh
# Runs only on host2      
#- hosts: host2
#  become: true
#  gather_facts: false
#  tasks:

#  - name: Install packages only on host1
#    yum:
#      name:
#        - bind-utils
#      state: latest
       


