# -*- mode: ruby -*-
# vim: set ft=ruby :

disk = './secondDisk.vdi'
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vbguest.auto_update = false

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.11.150"
    server.vm.provider "virtualbox" do |v|
      unless File.exist?(disk)
        v.customize ['createhd', '--filename', disk, '--variant', 'Fixed', '--size', 2 * 1024]
      end
      v.memory = 512
      v.cpus = 1
      v.customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
    end
    server.vm.hostname = "server"
  end


  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.11.151"
    client.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
    client.vm.hostname = "client"
  end

  config.vm.provision "BORG", type:'ansible' do |ansible|
    ansible.inventory_path = './provision/inventory'
    ansible.playbook = './provision/playbook.yml'
  end
end

