---
# handlers file for selinux
- name: restart php
  systemd:
    name: php-fpm
    state: restarted
    enabled: yes
#- name: enable mariadb
#  systemd:
#    name: mariadb
#    state: restarted
#    enabled: yes
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
