---
# tasks file for nginx
- name: Install percona-release
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - redhat-lsb-core
    - wget
    - rpmdevtools
    - rpm-build
    - createrepo
    - yum-utils
